# Site settings
title: Kavya Nori
email: kavya.nori@gmail.com
url: https://kavyanori.github.io
description: "Kavya Nori's personal website."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C0C0C0 #C0C0C0
  secondary: FFD700 #FD6E8A
  secondary-dark: 000000 #070f19 better than 000000

# Footer settings
footer:
  copyright: Kavya Nori
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/@krsna2498
  - title: facebook
    url: https://www.facebook.com/kavya.nori
  - title: linkedin
    url: https://www.linkedin.com/in/kavyanori
  - title: github
    url: http://github.com/kavyanori

# Postal address (add as many lines as necessary)
address:
  - line: 'Toronto, ON M9W 7J4'

# Credits content
credits:
  - line: <a href="mailto:kavya.nori@gmail.com" target="_top" style="color:white">kavya.nori@gmail.com</a>
  - line: (514) 778-2330

# Build settings
markdown: kramdown
permalink: pretty
